In [2]:
import pandas as pd
import numpy as np

1. 利用列表推导式写矩阵乘法

In [3]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

In [14]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
(np.abs((M1@M2 - res) < 1e-15)).all()

True

2. 更新矩阵

In [46]:
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a_2 = 1/a**2
a_2

array([[1.        , 0.25      , 0.11111111],
       [0.0625    , 0.04      , 0.02777778],
       [0.02040816, 0.015625  , 0.01234568]])

In [48]:
a_t = a_2.T
a_t

array([[1.        , 0.0625    , 0.02040816],
       [0.25      , 0.04      , 0.015625  ],
       [0.11111111, 0.02777778, 0.01234568]])

In [58]:
a_ = (a@a_t)[:,0]
a_

array([ 1.83333333,  5.91666667, 10.        ])

In [64]:
b = np.array([a[i,j]*a_[i] for j in range(a.shape[1]) for i in range(a_.shape[0])]).reshape(3,3, order='C')
b.T


array([[ 1.83333333,  3.66666667,  5.5       ],
       [23.66666667, 29.58333333, 35.5       ],
       [70.        , 80.        , 90.        ]])